### PR TITLE
[BUGFIX] Skip captcha validation of persisted mails (fixes #376)

### LINKED ISSUE #376: TYPO3 9.5 Double opt in: validation failed
Powermail 7
The Page shown after clicking the confirmation-Link in the mail show an error:

> Validation failed while trying to call In2code\Powermail\Controller\FormController->createAction(). 

All requried fields where filled out before. 
In file FormController.php on line 300 the createAction is called. After this the validation failed.
Can anybody confirm this issue?

### PR DESCRIPTION
**Pull request by vertexvaar**
Resolves: https://github.com/einpraegsam/powermail/issues/376
Resolves: https://projekte.in2code.de/issues/44174

### CODE REVIEW

**Comment by vertexvaar** [comment]
@einpraegsam This should also be merged upstream to your 8.x version

File: Classes/Domain/Validator/CaptchaValidator.php [hunk 1]
```diff
@@ -48,8 +48,16 @@ public function isValid($mail)
...
                     $this->setCaptchaArgument(true);
-                    if (!$this->validCodePreflight($answer->getValue(), $answer->getField())) {
-                        $this->setErrorAndMessage($answer->getField(), 'captcha');
+                    /* If the answer has a UID it has already been validated an persisted.
+                     * There's no reason to validate it twice. Also, there's no possibility, since the value to check
+                     * against got removed from the user's session on the first validation.
+                     * Resolves: https://github.com/einpraegsam/powermail/issues/376
+                     * Resolves: https://projekte.in2code.de/issues/44174
+                     */
+                    if (null === $answer->getUid()) {
```
Comment (einpraegsam) [inline Classes/Domain/Validator/CaptchaValidator.php:57]: Please don't use yoda conditions because we do not use it anywhere else. This has nearly no positive effect but makes readability much harder.

**Comment by einpraegsam** [comment]
Thx for your work while digging into the old code
